### ISSUE TITLE
Webpack Failed to compile Error: Can't resolve '@videojs/vhs-utils/dist/byte-helpers'

### ISSUE THREAD

**Issue by petebytes** [videojs/vhs-utils#25]
Upgraded video.js to 7.10.2 and vhs-utils from 2.2.1 to 3.0.0

Webpack
Failed to compile.
./node_modules/video.js/dist/video.es.js
Module not found: Error: Can't resolve '@videojs/vhs-utils/dist/byte-helpers' in '/app/node_modules/video.js/dist'

**Comment by gkatsev** [comment]
This is because vhs-utils is a breaking change that moves files around. Video.js 7.10 isn't set up to use it yet. Please continue to use vhs-utils 2.2.1.
