### ISSUE TITLE
Can we upgrade http://example.com to https://example.com?

### ISSUE THREAD

**Issue by wChenonly** [videojs/vhs-utils#39]
For some projects quality requirements must be https protocol in the code
Otherwise, it will be reported by the scanner  this http://example.com

Modern browsers can also automatically convert http to https

**Comment by mister-ben** [comment]
Here ? https://github.com/videojs/vhs-utils/blob/61b8db9f2d9b3085efe56050a6ad430ff03be55e/src/resolve-url.js#L4

I may as well add it to #38 as that changes that file

**Comment by wChenonly** [comment]
> Here ?
> 
> https://github.com/videojs/vhs-utils/blob/61b8db9f2d9b3085efe56050a6ad430ff03be55e/src/resolve-url.js#L4
> 
> I may as well add it to #38 as that changes that file

yes
